### ISSUE TITLE
Add open source license for pybezier

### ISSUE THREAD

**Issue by yungyuc** [jteng2127/pybezier#1]
@jteng2127 , please add an open source license for your project. If you are not sure how to do it, see https://github.com/solvcon/modmesh.

**Comment by yungyuc** [comment]
@jteng2127 , any update?

Based on [your schedule](https://github.com/yungyuc/nsdhw_24au/blob/ed6f48bf0412b8a5f9324cd055c49a4906700e8c/project/jteng2127/README.rst?plain=1#L167), there should be code in the repository last week.  Please update your progress.

**Comment by jteng2127** [comment]
Sorry, I've had some trouble with my time management recently, but things are gradually getting back on track.
I will start the development as soon as possible.
Thank you for the reminder.

**Comment by yungyuc** [comment]
No worry.  No one can predict the future and fully control the time.  When you get time to add the license file, please update in this issue.

**Comment by jteng2127** [comment]
Added in cf74929aa5015056d9284ef9b9a12a3770a3d620
