### ISSUE TITLE
Add work items to issues

### ISSUE THREAD

**Issue by yungyuc** [jteng2127/pybezier#3]
Please create issues according to your development plan in the proposal.

**Comment by yungyuc** [comment]
You are encouraged to review and participate the notes being developed in https://github.com/yungyuc/bezierfoil .  Don't hesitate to discuss with @YenPeiChen07 and @Gene0315 .

**Comment by yungyuc** [comment]
I saw you made progress week by week and it is good.  Organize and write down the rest in your plan to issues helps you think more about what to do.  Doing so improves your productivity.

**Comment by jteng2127** [comment]
Thanks! You're right, I'm not sure what is better to do next. Listing the issues helps me to figure out what do I need to do.
